### ISSUE TITLE
install/boot from SD card

### ISSUE THREAD

**Issue by ghost** [MozOpenHard/CHIRIMEN#10]
CHIRIMEN の仕様上ブートローダはどうしても NAND フラッシュに書き込んでおく必要があるが、カーネル等を SD カードに書き込んで使う事は技術的には可能。 NAND フラッシュの容量を気にしなくて済むほか、ファームウェアの配布・アップデートも SD カードの書き換えだけであれば比較的楽になると思われる。

ブートローダが Rockchip 独自のものの場合、カーネルおよび initramfs (boot.img) は NAND フラッシュに置くしかないが、他のブートローダであればカーネルを含め SD カードに置く事も可能になるはず。

**Comment by naokisekiguchi** [comment]
製造の際にこちらで用意したイメージを書き込んでおけることが前提となりますが、個人的にはCHIRIMENを手に入れてすぐ使えるという意味でNANDフラッシュにFirefoxOSを含めたシステム全体を格納しておくメリットも大きいと感じています。（raspberry piとの差分にもなる。）
macからの書き込みの問題等もあるので、最終的にファームウェアアップデートがどの程度簡単にできるようになるかにもかかってきますが。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#58
