### ISSUE TITLE
scroll bar position on Browser app

### ISSUE THREAD

**Issue by ghost** [MozOpenHard/CHIRIMEN#12]
ブラウザでスクロールバーが画面の真ん中に出てきます

![2015-04-25-171544](https://cloud.githubusercontent.com/assets/482349/7332194/cd806142-eb6e-11e4-84d0-8adcbd43303d.jpg)

**Comment by YusukeYamamoto** [comment]
phoneのビルドなのも影響しているかもしれませんね。。。
tablet, tv のビルドだとうまくいくかもしれないです。

デバッグすればすぐわかると思うので、実装も見てみたいなぁ。
※両方共GW入ってから・・

**Comment by YusukeYamamoto** [comment]
2.5では解消済み。
ただ、CHIRIMENとして2.5は正式サポートでは無いので、未CLOSEとしておく。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#60
