### ISSUE TITLE
ueventd.rc rules are not applied under certain conditions

### ISSUE THREAD

**Issue by ghost** [MozOpenHard/CHIRIMEN#14]
following rules are not applied under certain conditions.

```
/sys/devices/virtual/gpio/gpio*   direction   0666   root       root
/sys/devices/virtual/gpio/gpio*   value       0666   root       root
```

workaround: add `usleep(10000);` just before chown()/chmod() in system/core/init/devices.c:fixup_sys_perms()
(probably this is not correct fix...)

**Comment by masap** [comment]
This delay is required on gecko side also.

I have inserted `usleep(10000);` between exporting and setting direction.

**Comment by ghost** [comment]
workaround is commited https://github.com/MozOpenHard/platform_system_core/commit/4f177d0b25c259a9340329db0cea01c8feabce8e

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#62
