### ISSUE TITLE
Cannot use UART

### ISSUE THREAD

**Issue by naokisekiguchi** [MozOpenHard/CHIRIMEN#24]
This image cannot use UART feature. /dev/ttyS0 is not found.
http://dl.linux-rockchip.org/mozilla/mozopenhard_20150523.zip

**Comment by ghost** [comment]
currently most pins are configured as GPIO.

at first please enable CONFIG_UART0_RK29 and/or CONFIG_UART3_RK29 and recompile kernel.
probably some more tweaks are required to make it usable from Firefox OS.

---

"cannot use (something)" should be "make (something) work". it's not only UART, but also ADC, PWM, SPI, and maybe others. ;)
