### ISSUE TITLE
Chirimen-Dev Mailing List

### ISSUE THREAD

**Issue by arky** [MozOpenHard/CHIRIMEN#27]
Please kindly create a chirimen development (chirimen-dev) mailing-list. This will improve communication and help remote contributors to collaborate.  It is really difficult to keep track of conversations on Facebook group. Thanks!

**Comment by ghost** [comment]
:+1:

**Comment by stretchyboy** [comment]
:+1:  But how will we handle translation?

**Comment by naokisekiguchi** [comment]
:+1:  I had created a google group account named CHIRIMEN ( https://groups.google.com/forum/?hl=ja#!forum/chirimen ), but it's not used much. What settings are prefered? or should we create a new one?

**Comment by arky** [comment]
Not sure @stretchyboy you meant by translation. I used this URI to access English UI of Google Groups 
https://groups.google.com/forum/?hl=en#!forum/chirimen

**Comment by stretchyboy** [comment]
Many of the facebook group posts are in Japanese and Facebook sometimes
offers an automatic translation, which is helpful. I was wondering if
google groups includes a similar (or better ) feature.

On 9 September 2015 at 08:26, Arky notifications@github.com wrote:

> Not sure @stretchyboy https://github.com/stretchyboy you meant by
> translation. I used this URI to access English UI of Google Groups
> https://groups.google.com/forum/?hl=en#!forum/chirimen
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozOpenHard/CHIRIMEN/issues/27#issuecomment-138811663
> .

## 

Regards,

## Martyn

https://twitter.com/#!/stretchyboy

**Comment by YusukeYamamoto** [comment]
@dadaa, @dynamis, @naokisekiguchi  : It might be think that we'd like to be able to close this issue, we've already had the mailing list to discuss it, haven't we?

#Sorry to mention it to many perople. I'm not sure who is the project owner with CHIRIMEN to have a privilege to mange issues to close/open.

**Comment by dynamis** [comment]
We are now using MozOpenHard ML for anything about the project including CHIRIMEN dev:
https://groups.google.com/group/mozopenhard
and Slack for daily discussion:
http://mozoh.slack.com/

Feel free to write in english. We also write in English when we cross post to W3C or mozilla ML etc.
As for auto-translation, sorry for inconvenient but please use google translate or add-ons for it...

**Comment by autonome** [comment]
The mailing list is not open for anyone to join. Is there a reason to not
open it up?

**Comment by dadaa** [comment]
Oh, however this google group is "Shared publicly".
https://groups.google.com/group/mozopenhard
Couldn't you read mails?

**Comment by autonome** [comment]
ah, yes! i opened in a private browser window and could read them.

i had just subscribed, and the subscription said i had to apply to join. i
hope you will allow me to join. who would not be allowed to join?
