### ISSUE TITLE
Create #chirimen IRC Room

### ISSUE THREAD

**Issue by arky** [MozOpenHard/CHIRIMEN#28]
Please consider creating #chirimen and #chirimen-dev IRC rooms on irc.mozilla.org. The #chirimen is for users and general discussions and #chirimen-dev is for chirimen developer team. 

Thanks!

**Comment by ajsb85** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by autonome** [comment]
Would be great to have just one room for now, until the communication
volume is too overwhelming and we absolutely must have two.

**Comment by arky** [comment]
Agree with @autonome Let's keep it simple now.

**Comment by naokisekiguchi** [comment]
:+1:  How can we create the room?

**Comment by ghost** [comment]
@naokisekiguchi https://wiki.mozilla.org/IRC#Create_your_own_channel

**Comment by naokisekiguchi** [comment]
I have created and registered #chirimen room on irc.mozilla.org. Please try to access.

**Comment by ajsb85** [comment]
I'm ready connected with [Instantbird](http://instantbird.com/)

**Comment by arky** [comment]
Closing this bug as resolved. Thank you!
