### ISSUE TITLE
Add onboard RGB LED instead of Red LED

### ISSUE THREAD

**Issue by arky** [MozOpenHard/CHIRIMEN#30]
Add onboard RGB LED on future design of Chirimen. The Arduino boards has one built-in on digital pin 13. The RGB LED could be used to provide visual notification of boot errors and recovery mode #29  etc. We can use the RGB LED to provide interactive default demo app #26  as well

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#69
