### ISSUE TITLE
Fails on generate image file on flash.sh 

### ISSUE THREAD

**Issue by YusukeYamamoto** [MozOpenHard/CHIRIMEN#31]
[ problem ] 
In MozOpenHard repos, clone git repo. config it, build it, and then try to generate image to exec flash.sh.
We can't get image file.

[ cause ]
Chirimen's section is missing on flash.sh
We have to add bellows :

``` sh
 +"chirimen")
 +  cp device/rockchip/rksdk/buildspec-rk3066.mk ./buildspec.mk
 +  device/rockchip/rksdk/mkimage.sh
 +  rm ./buildspec.mk
 +  rkst/mkkrnlimg out/target/product/chirimen/kernel rockdev/Image/kernel.img
 +  exit 0
 +  ;;
```

**Comment by ghost** [comment]
see also: #13

**Comment by YusukeYamamoto** [comment]
対応済み。
ただし、2.5は正式対応ではないので、CLOSEさせないでおく。
※正式対応ではない = 誰が決定権もっているかわからないとも言う。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#70
