### ISSUE TITLE
最新のボードの綺麗な写真を用意する

### ISSUE THREAD

**Issue by dynamis** [MozOpenHard/CHIRIMEN#32]
ちゃんとしたカメラで撮影したボードの画像が素材として必要

**Comment by dynamis** [comment]
4k TVでじっくり見られても恥ずかしくない解像度でおねがいします ;) by naobsd

**Comment by kudodo** [comment]
http://web.sfc.wide.ad.jp/~kudo/tmp/CHIRIMEN600dpi.zip

こんなのでいかがですか？
ボードの汚れというか傷？がちょっときになるのでキレイなボードを今度さがします。

**Comment by dynamis** [comment]
ひとまず十分かと思います
https://github.com/MozOpenHard/CHIRIMEN-tools/tree/master/photoImages
に追加してこの issue は close いただければ

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#71
