### ISSUE TITLE
USB camera is not working

### ISSUE THREAD

**Issue by ghost** [MozOpenHard/CHIRIMEN#33]
https://github.com/flingone/hardware-rk29/commit/7a1a610b9f441dd54e7840db7e0b10bcf26c0338 this should be reverted.

**Comment by ghost** [comment]
in addition to hardware/rk29/, hardware/libhardware/ and bionic/ from Rockchip SDK are also required.

**Comment by ghost** [comment]
preview is not working. probably camera HAL need to be fixed.

https://github.com/flingone/hardware-rk29/blob/90003af61aca05a3c5d0404536bb66d1ae35c18d/camera/CameraHal.cpp#L3108
total was fewer than minimum.

I tried "total = numBufs+undequeued;" instead of "total = numBufs;". few preview frames were displayed, but it was not updated after that.

it might be better to check how it works on Android.

**Comment by dadaa** [comment]
OpenWebBoard can use USB camera,
http://flatbird.github.io/2014/11/21/owb-camera-api/
So, we may be able to refer OpenWebBoard source code.
http://opensource.kddi.com/owb/owbsource.html

**Comment by YusukeYamamoto** [comment]
+1
That's great idea.
 hardware > rk29 > Camera があやしい
あと、kernel > drivers > media > video

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#72
