### ISSUE TITLE
setup travis for MozOpenHard repo

### ISSUE THREAD

**Issue by YusukeYamamoto** [MozOpenHard/CHIRIMEN#35]
We have to run test suite on Gaia / Gecko for CHIRIMEN repo( MozOpenHard repo).

https://developer.mozilla.org/ja/Firefox_OS/Automated_testing/Gaia_integration_tests

**Comment by YusukeYamamoto** [comment]
The setup for travis was just setup by myself.

https://travis-ci.org/MozOpenHard

I'm going to check the travis to confirm to work test runner at commit or PR.
This issue is going to be still open until confirmed to work automatically test.

**Comment by YusukeYamamoto** [comment]
Close
it has already DONE.

**Comment by YusukeYamamoto** [comment]
reopen.
We've been get error on travis.
It seems that that error occurs on initial steps on CI.

**Comment by YusukeYamamoto** [comment]
It would be better to stop the travis CI for the time being until fix that error....

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#97
