### ISSUE TITLE
define default settings.json

### ISSUE THREAD

**Issue by dynamis** [MozOpenHard/CHIRIMEN#36]
Let's define and prepare appropriate default config for CHIRIMEN.

For example, I want: 
   "bluetooth.enabled": false,
   "debugger.remote-mode": "adb-devtools",
   "developer.menu.enabled": true,
   "devtools.debugger.remote-enabled": true,
   "devtools.remote.wifi.enabled": true,
   "geolocation.enabled": false,
   "lockscreen.passcode-lock.code": "0000",
   "lockscreen.passcode-lock.timeout": 0,
   "lockscreen.passcode-lock.enabled": false,
   "nfc.enabled": false,
   "screen.automatic-brightness": false,
   "screen.brightness": 1,
   "screen.timeout": 0,

config files in gaia
https://github.com/mozilla-b2g/gaia/tree/master/build/config
Note: my custome-setting.json for smartphone:
https://gist.github.com/dynamis/574b0cb2ed6668322f65

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#96
