### ISSUE TITLE
[Hardware Design] Improve Coin Cell Battery holder

### ISSUE THREAD

**Issue by arky** [MozOpenHard/CHIRIMEN#37]
The coin cell battery holder on OINARI device is quite delicate. With use the tensile strength of the battery snap might change making it unreliable. The design could be improved by choosing alternative battery holder such as standard coin cell holder (http://www.digikey.com/product-detail/en/107/36-107-ND/27387) or vertical coin cell holder (http://www.mouser.com/ProductDetail/Renata/NH5077-LF/?qs=SWRlsj5ucW7Bs86bh2iSGg%3D%3D).

/CC @dadaa

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#93
