### ISSUE TITLE
[Hardware Design] Add headers to CHIRIMEN board

### ISSUE THREAD

**Issue by arky** [MozOpenHard/CHIRIMEN#38]
It would be great to add female headers to Chirimen. This will make it easier to work. Most of the Arduino have this feature (http://www.arduino.cc/en/Main/ArduinoBoardUno).

Of course, It is quite simple to solder some male pins. But inexperienced users (like me) can easily end up damaging the board while soldering. The IC chips are closely spaced on CHIRIMEN, spilling some solder on IC chips would damage the board.

**Comment by autonome** [comment]
+1, anything requiring soldering should be avoided at all costs.

Arky, to illustrate the problem, can you describe what type of things users
_cannot_ do if there are no female headers on the board?

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#92
