### ISSUE TITLE
[Hardware Design] Add Onboard Communication WiFi module

### ISSUE THREAD

**Issue by arky** [MozOpenHard/CHIRIMEN#39]
It is cheaper now to have onboard WiFi onto the development boards. Adding support for basic networking by default would make IoT solutions much easier.

**Comment by autonome** [comment]
Once you have a radio on board, you have a FAR higher set of government
regulations that apply to the device. Not having onboard radio of any kind
means you can ship almost anywhere without needing government regulatory
approval.

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#91
