### ISSUE TITLE
[Hardware Design] Support for Stackable Sheilds 

### ISSUE THREAD

**Issue by arky** [MozOpenHard/CHIRIMEN#41]
In future we would like to add support to more sensors, Bluetooth, NFC and motor controls. Designing a new stackable shield would be great.

Alternatively Chirimen design could match the dimensions to Arudino Uno so that we can re-purpose Arudino Proto Sheild (http://www.arduino.cc/en/Main/ArduinoProtoShield). Users who have such Arudino uno compatible shields could start porting support to Firefox OS. 

Also consider looking at stackable solution out there such as Grove (http://www.seeedstudio.com/wiki/Grove_System) and Onion Omega (https://www.kickstarter.com/projects/onion/onion-omega-invention-platform-for-the-internet-of/description)

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#89
