### ISSUE TITLE
Port to master branch

### ISSUE THREAD

**Issue by YusukeYamamoto** [MozOpenHard/CHIRIMEN#43]
master ブランチで動かせるようにする。
現状、b2g-patches配下に CHIRIMEN用の各種パッチがあるが、これらを非適用もしくは、masterにいれられるよう検討する
方針として、まずはパッチをなくして代替手段がないかどうか(ビルドオプションとか)、
ない場合、パッチ削除による影響を確認する。

https://bugzilla.mozilla.org/show_bug.cgi?id=1166588 で指摘頂いている点についても解消必要。

**Comment by YusukeYamamoto** [comment]
#### [0001-gaia-Enable_ftu_to_exit_on_non-tiny_layout_device.patch](https://github.com/MozOpenHard/b2g-patches/blob/v2.5-kk-no_seccomp/0001-gaia-Enable_ftu_to_exit_on_non-tiny_layout_device-b2g44-v2.5.patch)

FTU の起動をさせないようにしている模様。
なので、ビルドオプションでNOFTU=1を指定してビルド
.userconfig で代替して、本patchは削除

**Comment by YusukeYamamoto** [comment]
#### [0001-gecko-Change_bootanimation_pixel_format.patch](https://github.com/MozOpenHard/b2g-patches/blob/v2.5-kk-no_seccomp/0001-gecko-Change_bootanimation_pixel_format-b2g44-v2.5.patch)

ブートアニメーションがおかしくなる?
ただ、対応をしないでも、ブートアニメーションの表示が崩れる等の影響しかないだろうから、パッチを当てなくても大丈夫そう。

**Comment by YusukeYamamoto** [comment]
#### [0001-gonk-misc_disable-content-sandbox.patch](https://github.com/MozOpenHard/b2g-patches/blob/v2.5-kk-no_seccomp/0001-gonk-misc_disable-content-sandbox-b2g44-v2.5.patch)

ac_add_options --disable-content-sandbox
ビルドオプション で行ける気がする。
継続して、要確認

**Comment by YusukeYamamoto** [comment]
#### [0002-gaia-Set_screen_timeout_to_never-b2g44-v2.5.patch](https://github.com/MozOpenHard/b2g-patches/blob/v2.5-kk-no_seccomp/0002-gaia-Set_screen_timeout_to_never-b2g44-v2.5.patch)

screen time outなので custom-settings.json に記載で行けそうな気がする。

ただ、custom-settings.json を置くにはbuildディレクトリ配下に置かなければならない。
しかし、buildディレクトリはflingoneのものを参照しているため、forkしてやる必要がありそう。

<project path="build" name="platform_build" remote="flingone" revision="flingone-kk">
    <copyfile src="core/root.mk" dest="Makefile"/>
  </project>

**Comment by YusukeYamamoto** [comment]
#### [0002-gecko-Enable_draw_mouse_cursor-b2g44-v2.5.patch](https://github.com/MozOpenHard/b2g-patches/blob/v2.5-kk-no_seccomp/0002-gecko-Enable_draw_mouse_cursor-b2g44-v2.5.patch)

マウスカーソルの対応。
カーソルのイメージの差し替えと、処理に色々手を加えている。
このパッチは必要そう。
なくすと、すくなくともカーソルサイズが小さくなる?
また、動作面でもどうなるは不明。

パッチ当てない状態での動作確認が必要。

03/22追記
define default settings.json
で対応可能

**Comment by YusukeYamamoto** [comment]
#### [0003-gecko-Map-mouse-right-button-to-home-b2g44-v2.5.patch](https://github.com/MozOpenHard/b2g-patches/blob/v2.5-kk-no_seccomp/0003-gecko-Map-mouse-right-button-to-home-b2g44-v2.5.patch)

右クリックをHomeKeyに割当
ソフトウェアHomeボタンの項目を有効にできれば消せそうだけど・・。

03/22追記
ソフトウェアHomeボタンを有効化するには、デバイスがモバイルとして認識されている必要がある。(※1)
※試しに、無理やり適用したが、ボタンが画面の横に表示されてしまう。モバイルとして縦画面想定なので、Rotateした状態と認識してしまっている。今はなき tablet ビルドなら問題なさそうなのだけれど。。。

※1
gaia/apps/system/js/software_button_manager.js
isMobileがtrueになることが必要。
取得メソッドが以下
gaia/shared/js/screen_layout.js
getCurrentLayout()

**Comment by YusukeYamamoto** [comment]
#### [0004-gaia-Set_device.storage.writable.name_to_internal_sd-b2g44-v2.5.patch](https://github.com/MozOpenHard/b2g-patches/blob/v2.5-kk-no_seccomp/0004-gaia-Set_device.storage.writable.name_to_internal_sd-b2g44-v2.5.patch)

"device.storage.writable.name"に"internal_sd"を設定。

#57  SDカードの有効化を考慮する必要あり。

**Comment by YusukeYamamoto** [comment]
#### 0004-gecko-gfx_add_NV12_format-b2g44-v2.5.patch

サーフェースのピクセルフォーマットに"HAL_PIXEL_FORMAT_YCrCb_NV12"を追加。

OpenGLのtextures処理に影響があると思われる(未確認)。
Rockchip上でAndroid環境を動作する場合に影響がある模様。なので消しても問題なさそうな。。。

**Comment by YusukeYamamoto** [comment]
#### 0005-gecko-add_more_popular_mimetypes-b2g44-v2.5.patch

メディアデコーダー(OMX)に"video/x-flv"、"video/x-f4v"等のメディア種別を追加。

該当フォーマットのストリーミング再生が出来ない。
PC の ブラウザとしてのFirefox も再生対応していない部分。

**Comment by YusukeYamamoto** [comment]
#### 0006-gecko-clear_addrs-b2g44-v2.5.patch

Wi-FiのON/OFF時にエラーとなる問題の対応と思われるが、、、

試しに本パッチを非適用で動作させてみたが、ログではWi-Fi関連のエラーが出力されている。
しかし、普通に使えている。実害については、不明。
不要ではないか。

**Comment by YusukeYamamoto** [comment]
#### 0007-gecko-enable-rtsp-streaming-protocol-support-b2g44-v2.5.patch

geckoにRTSPプロトコルを追加。
RTSP プロトコルを必要として追加している背景が不明。
なくても良さそう。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#88
