### ISSUE TITLE
recomplie kernel  with enable SECCOMP

### ISSUE THREAD

**Issue by YusukeYamamoto** [MozOpenHard/CHIRIMEN#45]
Slackなどで話している件。
https://mozoh.slack.com/messages/porting/details/

Issueで残せていなかったので立てときます。
※Issueにすでにあり,duplicateなら要削除。

CONFIG_SECCOMP_FILTER=y してカーネルのリコンパイル

Mozilla Japanさんで対応中の認識なのでAssignee更新。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#86
