### ISSUE TITLE
Change default SCL clock frequency to 100 kbps (standard-mode)

### ISSUE THREAD

**Issue by dadaa** [MozOpenHard/CHIRIMEN#48]
I tried to use a following sensor AM2320, but the sensor could not work.
http://akizukidenshi.com/download/ds/aosong/AM2320.pdf
Also I did i2cdetect command on CHIRIMEN, but it was not detected.
According to the spec, this sensor supports up to 100khz SCL clock frequency.
Other sensors that are working well support 400khz.
So the reason may be the frequency.

standard-mode: up to 100 kbit/s.
fast-mode: up to 400 kbit/s
fast-mode plus: up to 1000 kbit/s
HS-mode: up to 3.4 Mbit/s.

**Comment by dynamis** [comment]
To support more devices, default build should use standard-mode (rebuild karnel if you want to use fast mode)

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#84
