### ISSUE TITLE
WebGPIO & WebI2C 実装を Worker スレッドに

### ISSUE THREAD

**Issue by dynamis** [MozOpenHard/CHIRIMEN#51]
今は Navigator を使ってるが WorkerNavigator (実装) とか使って Device Worker を立てていく形に

**Comment by YusukeYamamoto** [comment]
- [ ] WorkerNavigator 経由で WebGPIO の各メソッド を呼べるようにする
- [ ] WorkerNavigator 経由で WebI2C の各メソッド を呼べるようにする

**Comment by dadaa** [comment]
i2c
https://github.com/MozOpenHard/gecko-dev/pull/1
gpio
https://github.com/MozOpenHard/gecko-dev/pull/2

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#80
