### ISSUE TITLE
limit GPIO/I2C API access from background apps

### ISSUE THREAD

**Issue by dynamis** [MozOpenHard/CHIRIMEN#52]
現在バックグラウンドアプリ (タブ) からでも GPIO/I2C が操作可能。

WebRTC とか Audio とか同時に多数のアプリからつかるような API はバックグラウンドでも使えるが Vibration のような排他的なものはフォアグラウンドからだけ使えるのが多分普通。GPIO/I2C についてもフロント (現在) のアプリだけで動作するようにするのがよさそう。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#79
