### ISSUE TITLE
change device name shown in WebIDE

### ISSUE THREAD

**Issue by dynamis** [MozOpenHard/CHIRIMEN#54]
Current CHRIMEN is recognized as "Firefox OS (CHIRIMEN)".
We'll change this to just "CHIRIMEN"

**Comment by dadaa** [comment]
This "Firefox OS($devicename)" is defined in ADB Helper addon.
https://github.com/mozilla/adbhelper/blob/master/scanner.js#L136
How can we resolve..

**Comment by autonome** [comment]
Have you submitted a pull-request to that repo?

**Comment by dadaa** [comment]
not yet...
I'll try to pull request to display only device name.

**Comment by dadaa** [comment]
I sent pull request to AdbHelper.
https://github.com/mozilla/adbhelper/pull/26

**Comment by dadaa** [comment]
This pull request was merged to mozilla/adbhelper.
I close this issue.

**Comment by dadaa** [comment]
The addon with that change was released in version 0.8.7.
https://ftp.mozilla.org/pub/labs/fxos-simulator/adb-helper/
