### ISSUE TITLE
to add "dom.gpio.enabled" prefs ( also i2c )

### ISSUE THREAD

**Issue by YusukeYamamoto** [MozOpenHard/CHIRIMEN#55]
TV Manager APIの実装を見ると、b2g.js にprefsで設定値を指定の上、機能の有効無効を切り替えている。
つまり、TV以外ではTV Magaerは動かないようにしている。
https://github.com/mozilla/gecko-dev/commit/d12e06f1df4a99f54af28df13d09f55fc0f34924

デバイス操作系のAPIについても性質上、同じように実装したほうが好ましい。
※Bugillaでのレビューから指摘はもらってないが、同じ指摘が来ると想像できる

**Comment by YusukeYamamoto** [comment]
### gaia 上での実装
- [ ] dom.gpio.enabled の追加
- [ ] dom.i2c.enabled の追加

### gecko 上での実装
- [ ] web gpio系の有効無効を切り替える
- [ ] web i2c系の有効無効を切り替える

※Geckoの方はもう少しブレークダウンの必要あり。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#77
