### ISSUE TITLE
JSライブラリの修正

### ISSUE THREAD

**Issue by YusukeYamamoto** [MozOpenHard/CHIRIMEN#56]
議論した仕様にしたがって、webgpio.js/webi2c.jsの修正を行う
https://docs.google.com/document/d/15CJ2rqeY_AfzI8l3IMFRO48N7Y1cAg9etx_JyPLzwKc/edit

仕様通りにAPIの修正、jsonから定数を呼べるようにするがメイン?
→修正されたライブラリに合わせる形でサンプルアプリの修正も必要。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#76
