### ISSUE TITLE
Prepare english documents for build and install

### ISSUE THREAD

**Issue by dynamis** [MozOpenHard/CHIRIMEN#58]
We currently have this page in wiki
https://github.com/MozOpenHard/CHIRIMEN/wiki/Setup

but it don't contain enough/full information like this:
https://github.com/MozOpenHard/CHIRIMEN-tools/blob/master/doc/installFirefoxOS.pdf

let's prepare english documents to work with global contributors.
I believe this document should be prepared before the general availability (-> Milestone 1).

**Comment by dynamis** [comment]
Better to write in MDN?
https://developer.mozilla.org/en-US/Firefox_OS/Board_guide/CHIRIMEN
or write in our Wiki and link from MDN?

I prefer to write in MDN since it support l10n and we can find relating information about porting to other boards (will coming soon?) within the same site.

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#74
