### ISSUE TITLE
Identify what documents we must prepare

### ISSUE THREAD

**Issue by dynamis** [MozOpenHard/CHIRIMEN#59]
Let's define the priority or milestone of the documents we need to prepare
- spec
  - http://mozopenhard.mozillafactory.org/techinfo#hardspec
- how to build and install instruction #58 
- how to use WebGPIO & WebI2C
- Spec and native implementation + polyfil
- existing sample codes and libraries for know GPIO/I2C devices
- how to write your own library for your own GPIO/I2C device

Where we'll write these information? MDN or Wiki or mozopnehard web site (tumblr)?
I prefer MDN since it support l10n to write both english and Japanese.

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#73
