### ISSUE TITLE
GPIO/I2C implementation issues

### ISSUE THREAD

**Issue by YusukeYamamoto** [MozOpenHard/CHIRIMEN#62]
# ■ コードレビュー

Sorry, there are Japanese Only.

現状の GPIO/I2C の実装を Gecko master に組み込むための課題となります。

既知の問題点含め本Issueにまとめて記載します。
※また、未来に対応される方の為に、修正範囲ではない箇所についても記載しています。
### ● web workersへの実装

Gecko の設計上、 WorkerNavigatro に実装するのが正しい姿か。
おそらく、Moz Reviewした際に指摘が来ると思われます。
web workersのNavigatorであるWorkerNavigatorは、  
ブラウザの情報を取得するためのオブジェクトであり、APIの処理を行うものではないのではないか懸念があります。
ここに、GPIO, I2Cを実装するのは、強引と言われないか。
### ● 関数が同期となっている

Web workers対応により、メインスレッドのブロックについては、回避されています。しかし、次のようなユースケースにおいて、別の問題が発生する。  
Web workersで測定した値を UI に表示し、値を更新するケースを想定する。この場合、非常に短い間隔で更新が必要な場合に、メインスレッドと頻繁にメッセージのやり取りが発生し、実装が複雑化するのではないか、懸念点として残る。
※APIが同期処理を前提としているため、このように非常に短い間隔での更新をターゲットとした場合の懸念

ここは、APIを非同期化し、メインスレッドでデバイスに変化があった場合のみ、Gecko層から通知するようにしたほうが実装が簡素化されるのではないか。
### ● リソース(GPIO, I2C)が使用中なのかどうかが、判断できない。

GPIO, I2Cに割り当てたリソースをあるアプリが使用している場合に、そのリソースに対してアプリからリソース確保の要求をした際、内部的に処理をブロックしている。  

https://github.com/MozOpenHard/gecko-dev/blob/43e3b0010a43d8d6840dc8c3397a09693a806f64/dom/gpio/GpioService.cpp#L44-L47

そのまま NS_OK を return しており、アプリ側で正しくリソース確保できたか判断がつかない。
対応方法としては、戻り値を NS_OK 以外( NS_ERROR_FAILURE など) にして、
　引数を追加してエラーを返す、
　getError などのAPIを追加し、エラー返却時はエラー詳細を取得するようにする
など。
※個人的には後者が好みですが。。。
### ● navigator.mozGpio.exportを使用する場合、アプリで遅延処理が必要

アプリから以下のように、navigator.mozGpio.export()を連続実行した場合、エラーが発生する。

```
navigator.mozGpio.export(198);
navigator.mozGpio.export(199);
navigator.mozGpio.export(256);
  .....
```

現状、アプリから以下のように遅延処理を入れることで回避できるが、
本来、APIの実装側で吸収すべきものと指摘が来る可能性あり。

```
navigator.mozGpio.export(198);
 *** delay ***
navigator.mozGpio.export(199);
 *** delay ***
navigator.mozGpio.export(256);
```
### ● アプリが、エラーをハンドリングできない

上記の「navigator.mozGpio.exportを使用する場合、遅延処理が必要」のようなケースを含めて、  
アプリが、エラーをハンドリングできない。
### ● usleepを使用している

export()後、直ぐにdirection()を実行した場合、Permission Deniedのエラーが発生する。  
これの回避策として、usleep()を使用している。
### ● Gecko層で発生した内部的なエラーを補足していない。

基本的にAPIは、アプリに対してエラーを通知しない。  
アプリから見た場合、全て成功した扱いになる。  
上記の「アプリが、エラーをハンドリングできない」と関連する。
### ● エラー時の戻り値が適切ではない。

非同期であれば、onerrorでエラーを通知するのが、適切であるが、  
現状、同期処理なので何らかの値を返却しなければならいため適当な値が返却されている。

特に以下のAPIについては、適切ではない。

gecko/dom/gpio/GpioManager.cpp

```
uint32_t
GpioManager::GetValue(uint32_t aPinNo)
{
  uint32_t aValue;

  nsCOMPtr<nsIGpioService> gpioService = do_GetService(GPIOSERVICE_CONTRACTID);
  if (gpioService) {
    gpioService->GetValue(aPinNo, &aValue); ..... (1)
    return aValue;
  }
  return 12345; ..... (2)
}
```

(1)ここでエラーが発生しても、アプリとしては、成功となり正しい値が返却されたと判断される。  
(2) 12345 という値を返却しており適切ではない。

gecko/dom/i2c/I2cManager.cpp

```
uint16_t
I2cManager::Read(uint8_t aDeviceNo, uint8_t aCommand, bool aIsOctet)
{
  .....
  return 12345; ..... (3)
}
```

(3)この値も適切ではない。I2Cの場合、「12345」は、成功時もあり得る値である。
### ● テストコードがない

APIを実行する最低限のテストコードが必要と思われる。  
また、Geckoの本線にアップする際には、Mozillaのルールに従ったテストコードが必要である。
### ● コード規約に反している

 https://developer.mozilla.org/ja/docs/Mozilla_Coding_Style_Guide

　nsAutoString, nsCAutoStringではなく、nsCStringを使用している
## その他

懸念点としてスレッドセーフになっているのか?  
リソースが一つしかないので、誰かがそのリソースを占有した場合、内部的に処理をブロックしている。  
なので、問題ないか。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#53
