### ISSUE TITLE
bootloader

### ISSUE THREAD

**Issue by ghost** [MozOpenHard/CHIRIMEN#9]
CHIRIMEN (RK3066) で利用可能なものとしては主に以下の二つ。
- Rockchip 独自
- U-Boot (Rockchip による fork 版)

Rockchip 独自のものは安定しているが、 U-Boot の方は OTG からのイメージの書き込みが不安定。
U-Boot の方は fastboot 対応。 (ただし現状のものはバグで使えない気がする)

現状 U-Boot でイメージの書き込みに失敗する事がそれなりにあるので、 Rockchip 独自のものにする方がよいかもしれない。
(ボードの数が少なく作業者が限られている為、周知しておけば済むという考えもアリ?)

**Comment by ghost** [comment]
「U-Boot でイメージの書き込みに失敗する事がそれなりにある」件ですが、 cold boot (RECOVER押しながら電源オン) だと不安定で warm boot (正常に起動した状態からadb reboot bootloader等) だと安定しているような気がしてきました。

**Comment by MSakamaki** [comment]
This issue was moved to chirimen-oh/any-issues#57
